package com.gladimdim.omakey.protocol

import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.security.SecureRandom

/**
 * Reproduces docs/test-vectors.json from the daemon repo (generated by
 * `omakeyd test-vectors`) byte for byte. Refresh the copy in
 * src/test/resources whenever the daemon regenerates it.
 */
class TestVectorsTest {
    private val v = JSONObject(
        javaClass.getResourceAsStream("/test-vectors.json")!!.readBytes().toString(Charsets.UTF_8),
    )

    private fun hex(name: String, obj: JSONObject = v) = Hex.decode(obj.getString(name))

    /** Hands out the vector's random bytes in the order the client asks for them. */
    private class FixedRandom(vararg chunks: ByteArray) : SecureRandom() {
        private val queue = ArrayDeque(chunks.toList())
        override fun nextBytes(bytes: ByteArray) {
            val next = queue.removeFirst()
            require(next.size == bytes.size) { "asked for ${bytes.size} bytes, vector has ${next.size}" }
            next.copyInto(bytes)
        }
    }

    @Test
    fun pairUriMatches() {
        val h = PairingUri.parse(v.getString("pair_uri"))
        assertEquals(v.getString("host_id"), h.hostId)
        assertEquals("omarchy desk", h.name)
        assertArrayEquals(hex("device_id"), h.deviceId)
        assertArrayEquals(hex("device_key"), h.key)
        assertEquals(listOf("192.168.50.219", "100.67.193.30"), h.addresses)
        assertEquals(47800, h.port)
    }

    @Test
    fun sessionKeysMatch() {
        val k = SessionKeys.derive(hex("device_key"), hex("client_random"), hex("server_random"))
        assertEquals(v.getString("kcs"), Hex.encode(k.clientToServer))
        assertEquals(v.getString("ksc"), Hex.encode(k.serverToClient))
    }

    @Test
    fun wholeSessionMatchesByteForByte() {
        val host = PairingUri.parse(v.getString("pair_uri"))
        val hello = v.getJSONObject("hello")
        val keys = KeyState()
        val client = ClientSession(
            host, hello.getString("name"), keys,
            FixedRandom(hex("client_random"), hex("nonce", hello)),
        )

        assertEquals(hello.getString("packet"), Hex.encode(client.helloPacket()))

        val welcome = hex("packet", v.getJSONObject("welcome"))
        val connected = client.receive(welcome, welcome.size, 0) as ClientSession.Result.Connected
        assertEquals(v.getJSONObject("welcome").getString("host_name"), connected.hostName)
        assertEquals(v.getInt("session_id"), connected.sessionId)

        val in1 = v.getJSONObject("input1")
        assertTrue(keys.press(125))
        assertEquals(in1.getString("packet"), Hex.encode(client.inputPacket(in1.getInt("client_time_ms"))!!))

        val in2 = v.getJSONObject("input2")
        assertTrue(keys.press(57))
        assertEquals(in2.getString("packet"), Hex.encode(client.inputPacket(in2.getInt("client_time_ms"))!!))

        val ackV = v.getJSONObject("ack")
        val ack = hex("packet", ackV)
        val now = ackV.getInt("client_time_ms") + 5
        assertEquals(ClientSession.Result.Acked(5), client.receive(ack, ack.size, now))
        assertEquals(false, keys.hasUnacked)

        assertEquals(v.getJSONObject("bye").getString("packet"), Hex.encode(client.byePacket()!!))
    }
}
